name: 'dbt_with_datacontracts'
version: '1.0.0'

profile: 'dbt_with_datacontracts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  +persist_docs:
    relation: true
    columns: true

clean-targets:
  - "target"
  - "dbt_packages"
