"""Tests for the Config model."""

import pytest
from pydantic import ValidationError

from dbt_contracts.models.config import Config, GenerationConfig


class TestConfigDefaults:
    def test_empty_config(self):
        config = Config()
        assert config.project_name is None
        assert config.dbt_project_dir == ".."
        assert config.default_server_type == "snowflake"
        assert config.generation is None
        assert config.validation is None

    def test_generation_defaults(self):
        gen = GenerationConfig()
        assert gen.models_dir == "models/generated"
        assert gen.generate_sources is True
        assert gen.generate_tests is True
        assert gen.header == "-- Generated by dbt-contracts. Do not edit manually."


class TestConfigFromDict:
    def test_full_config(self):
        config = Config(
            project_name="my-project",
            dbt_project_dir="..",
            default_server_type="bigquery",
            generation=GenerationConfig(
                models_dir="models/contracts",
                generate_sources=False,
            ),
        )
        assert config.project_name == "my-project"
        assert config.default_server_type == "bigquery"
        assert config.generation.models_dir == "models/contracts"
        assert config.generation.generate_sources is False
        assert config.generation.generate_tests is True


class TestConfigFromString:
    def test_from_yaml_string(self):
        yaml_str = """
project_name: test-project
default_server_type: postgres
generation:
  models_dir: models/gen
  generate_tests: false
validation:
  min_status: active
"""
        config = Config.from_string(yaml_str)
        assert config.project_name == "test-project"
        assert config.default_server_type == "postgres"
        assert config.generation.models_dir == "models/gen"
        assert config.generation.generate_tests is False
        assert config.validation.min_status == "active"

    def test_from_empty_string(self):
        config = Config.from_string("")
        assert config.project_name is None
        assert config.dbt_project_dir == ".."


class TestConfigFromFile:
    def test_load_from_file(self, tmp_path):
        config_file = tmp_path / "config.yaml"
        config_file.write_text(
            "project_name: file-project\ndefault_server_type: redshift\n"
        )
        config = Config.from_file(str(config_file))
        assert config.project_name == "file-project"
        assert config.default_server_type == "redshift"

    def test_file_not_found(self):
        with pytest.raises(FileNotFoundError):
            Config.from_file("/nonexistent/config.yaml")


class TestConfigToYaml:
    def test_roundtrip(self):
        config = Config(
            project_name="roundtrip",
            default_server_type="bigquery",
        )
        yaml_str = config.to_yaml()
        restored = Config.from_string(yaml_str)
        assert restored.project_name == "roundtrip"
        assert restored.default_server_type == "bigquery"

    def test_excludes_defaults(self):
        config = Config(project_name="only-this")
        yaml_str = config.to_yaml()
        assert "project_name" in yaml_str
        assert "dbt_project_dir" not in yaml_str
        assert "default_server_type" not in yaml_str


class TestConfigValidation:
    def test_extra_fields_rejected(self):
        with pytest.raises(ValidationError):
            Config(project_name="test", unknown_field="bad")

    def test_nested_with_partial_fields(self):
        config = Config(
            generation=GenerationConfig(models_dir="custom/path"),
        )
        assert config.generation.models_dir == "custom/path"
        assert config.generation.generate_sources is True
