"""Tests for the dbt artifact generator."""

from pathlib import Path

from dbt_contracts.core.discovery import discover
from dbt_contracts.core.generator import GenerateResult, generate
from dbt_contracts.models.config import GenerationConfig

FIXTURES = Path(__file__).parent / "fixtures"
SAMPLE_PROJECT = FIXTURES / "sample_project"


class TestGenerate:
    def test_returns_generate_result(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path)
        assert isinstance(result, GenerateResult)

    def test_generates_model_yml_and_sql(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path)
        paths = {f.path.name for f in result.files}
        assert "stg_orders.yml" in paths
        assert "stg_orders.sql" in paths

    def test_generates_sources_yml(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path)
        source_files = [f for f in result.files if "raw-customers" in f.path.name]
        assert len(source_files) == 1
        assert source_files[0].path.name == "raw-customers.yml"

    def test_respects_models_dir(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path, models_dir="custom/models")
        model_files = [f for f in result.files if f.path.name.endswith(".sql")]
        for f in model_files:
            assert "custom/models" in str(f.path)

    def test_respects_sources_dir(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path, sources_dir="custom/sources")
        source_files = [f for f in result.files if "raw-customers" in f.path.name]
        for f in source_files:
            assert "custom/sources" in str(f.path)

    def test_header_prepended_to_yaml(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path)
        yml_files = [f for f in result.files if f.path.suffix == ".yml"]
        for f in yml_files:
            assert f.content.startswith("# -- Generated by dbt-contracts")

    def test_header_prepended_to_sql(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path)
        sql_files = [f for f in result.files if f.path.suffix == ".sql"]
        for f in sql_files:
            assert f.content.startswith("-- Generated by dbt-contracts")

    def test_files_written_to_disk(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path)
        for f in result.written:
            assert f.path.exists()
            assert f.path.read_text(encoding="utf-8") == f.content


class TestGenerateConfig:
    def test_strip_tests_when_disabled(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        discovery.config.generation = GenerationConfig(generate_tests=False)
        result = generate(discovery, output_base=tmp_path)
        yml_files = [
            f
            for f in result.files
            if f.path.suffix == ".yml" and "stg_orders" in f.path.name
        ]
        for f in yml_files:
            assert "data_tests" not in f.content

    def test_skip_sources_when_disabled(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        discovery.config.generation = GenerationConfig(generate_sources=False)
        result = generate(discovery, output_base=tmp_path)
        source_files = [f for f in result.files if "raw-customers" in f.path.name]
        assert source_files == []


class TestOverwriteProtection:
    def test_overwrites_managed_file(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        # First generate
        generate(discovery, output_base=tmp_path)
        # Second generate should overwrite
        result = generate(discovery, output_base=tmp_path)
        assert all(not f.skipped for f in result.files)

    def test_skips_unmanaged_file(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        # Create a file without the header
        models_dir = tmp_path / "models" / "generated"
        models_dir.mkdir(parents=True)
        unmanaged = models_dir / "stg_orders.yml"
        unmanaged.write_text("# User-written file\nversion: 2\n")
        result = generate(discovery, output_base=tmp_path)
        stg_file = next(f for f in result.files if f.path.name == "stg_orders.yml")
        assert stg_file.skipped is True

    def test_force_overwrites_unmanaged(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        models_dir = tmp_path / "models" / "generated"
        models_dir.mkdir(parents=True)
        unmanaged = models_dir / "stg_orders.yml"
        unmanaged.write_text("# User-written file\nversion: 2\n")
        result = generate(discovery, output_base=tmp_path, force=True)
        stg_file = next(f for f in result.files if f.path.name == "stg_orders.yml")
        assert stg_file.skipped is False


class TestDryRun:
    def test_dry_run_does_not_write(self, tmp_path):
        discovery = discover(SAMPLE_PROJECT)
        result = generate(discovery, output_base=tmp_path, dry_run=True)
        assert len(result.files) > 0
        for f in result.files:
            assert not f.path.exists()
