version: 2
sources:
- name: payments
  tables:
  - name: payments
    description: Payment transaction records
    columns:
    - name: payment_id
      data_tests:
      - not_null
      data_type: VARCHAR
      description: Unique payment identifier
    - name: customer_id
      data_tests:
      - not_null
      data_type: VARCHAR
      description: Reference to the customer
    - name: amount
      data_tests:
      - not_null
      data_type: NUMBER
      description: Payment amount in cents
    - name: thingy
      data_tests:
      - not_null
      data_type: NUMBER
      description: Thingy Payment amount in cents
