"""dbt artifact generation from discovered contracts and products.

Orchestrates the full generation flow: render via adapter, post-process,
and write files to the dbt project directory.
"""

from __future__ import annotations

from pathlib import Path

import pydantic as pyd
import yaml

from dbt_contracts.core.adapter import render
from dbt_contracts.core.discovery import DiscoveryResult


class GeneratedFile(pyd.BaseModel):
    """A file produced by the generator."""

    path: Path
    content: str
    skipped: bool = False


class GenerateResult(pyd.BaseModel):
    """Result of running the generator."""

    files: list[GeneratedFile] = pyd.Field(default_factory=list)

    @property
    def written(self) -> list[GeneratedFile]:
        return [f for f in self.files if not f.skipped]

    @property
    def skipped_files(self) -> list[GeneratedFile]:
        return [f for f in self.files if f.skipped]


def generate(
    discovery: DiscoveryResult,
    output_base: Path,
    models_dir: str | None = None,
    sources_dir: str | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> GenerateResult:
    """Generate dbt artifacts from discovered contracts and products.

    Args:
        discovery: Result from discover().
        output_base: Base path for output (typically the dbt project root).
        models_dir: Override for models output directory.
        sources_dir: Override for sources output directory.
        force: Overwrite non-managed files.
        dry_run: Preview without writing files.

    Returns:
        GenerateResult with all generated (or previewed) files.
    """
    gen_config = discovery.config.generation
    resolved_models_dir = output_base / (
        models_dir or (gen_config.models_dir if gen_config else "models/generated")
    )
    resolved_sources_dir = output_base / (
        sources_dir or (gen_config.sources_dir if gen_config else "models/staging")
    )
    header = (
        gen_config.header
        if gen_config
        else "-- Generated by dbt-contracts. Do not edit manually."
    )
    gen_sources = gen_config.generate_sources if gen_config else True
    gen_tests = gen_config.generate_tests if gen_config else True

    default_server_type = discovery.config.default_server_type or "snowflake"

    contracts = [dc.contract for dc in discovery.contracts]
    products = [dp.product for dp in discovery.products]
    rendered = render(contracts, products, default_server_type)

    files: list[GeneratedFile] = []

    # Sources
    if gen_sources:
        for source_dict in rendered.sources:
            source_name = source_dict.get("sources", [{}])[0].get("name", "sources")
            yaml_str = _to_yaml(source_dict)
            content = _prepend_yaml_header(yaml_str, header)
            path = resolved_sources_dir / f"{source_name}.yml"
            files.append(GeneratedFile(path=path, content=content))

    # Models
    for model_dict in rendered.models:
        for model in model_dict.get("models", []):
            model_name = model.get("name", "model")
            single_model_dict = {"version": 2, "models": [model]}

            if not gen_tests:
                _strip_tests(single_model_dict)

            yaml_str = _to_yaml(single_model_dict)
            content = _prepend_yaml_header(yaml_str, header)
            path = resolved_models_dir / f"{model_name}.yml"
            files.append(GeneratedFile(path=path, content=content))

    # Staging SQL
    for model_name, sql in rendered.staging_sql.items():
        content = _prepend_sql_header(sql, header)
        path = resolved_models_dir / f"{model_name}.sql"
        files.append(GeneratedFile(path=path, content=content))

    # Write or preview
    if not dry_run:
        for f in files:
            if f.path.exists() and not _is_managed_file(f.path, header) and not force:
                f.skipped = True
                continue
            f.path.parent.mkdir(parents=True, exist_ok=True)
            f.path.write_text(f.content, encoding="utf-8")

    return GenerateResult(files=files)


def _to_yaml(data: dict) -> str:
    """Serialize a dict to YAML string."""
    return yaml.dump(data, sort_keys=False, allow_unicode=True)


def _prepend_yaml_header(yaml_str: str, header: str) -> str:
    """Prepend a header comment to a YAML string."""
    comment = f"# {header}\n"
    return comment + yaml_str


def _prepend_sql_header(sql: str, header: str) -> str:
    """Prepend a header comment to a SQL string."""
    return f"{header}\n{sql}"


def _strip_tests(model_dict: dict) -> None:
    """Remove data_tests from model columns and model-level tests."""
    for model in model_dict.get("models", []):
        model.pop("data_tests", None)
        for column in model.get("columns", []):
            column.pop("data_tests", None)


def _is_managed_file(path: Path, header: str) -> bool:
    """Check if an existing file was generated by dbt-contracts."""
    try:
        first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
        return header in first_line
    except OSError:
        return False
