version: 2
models:
- name: customer_summary
  config:
    meta:
      data_contract: a1234567-b890-cdef-1234-567890abcdef
      domain: seller
    materialized: table
    contract:
      enforced: true
  description: Aggregated customer metrics
  columns:
  - name: customer_id
    data_type: VARCHAR
    description: Unique customer identifier
    constraints:
    - type: not_null
    - type: unique
  - name: total_payments
    data_type: NUMBER
    description: Total payment amount
    constraints:
    - type: not_null
  - name: last_payment_date
    data_type: TIMESTAMP_TZ
    description: Date of most recent payment
